[package]
name = "egomoose/raycast-helper"
description = "https://github.com/EgoMoose/raycast-helper"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["test", "assets"]

[dependencies]
